"""init tables

Revision ID: b9f9be05ce93
Revises: 
Create Date: 2026-07-10 01:10:07.590001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9f9be05ce93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cod_surcharge_config',
    sa.Column('order_type', sa.Enum('B2B', 'B2C', name='ordertype'), nullable=False),
    sa.Column('surcharge_type', sa.Enum('FLAT', 'PERCENT', name='surchargetype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'AGENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('zones',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_zone_id', sa.UUID(), nullable=True),
    sa.Column('current_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('active_order_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rate_cards',
    sa.Column('zone_from_id', sa.UUID(), nullable=False),
    sa.Column('zone_to_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.Enum('B2B', 'B2C', name='ordertype'), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_from_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['zone_to_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_pincodes',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_pincodes_pincode'), 'zone_pincodes', ['pincode'], unique=True)
    op.create_table('orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('drop_address', sa.Text(), nullable=False),
    sa.Column('pickup_zone_id', sa.UUID(), nullable=False),
    sa.Column('drop_zone_id', sa.UUID(), nullable=False),
    sa.Column('length_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('breadth_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('actual_weight_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('volumetric_weight_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('billable_weight_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('order_type', sa.Enum('B2B', 'B2C', name='ordertype'), nullable=False),
    sa.Column('payment_type', sa.Enum('PREPAID', 'COD', name='paymenttype'), nullable=False),
    sa.Column('charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('current_status', sa.Enum('CREATED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'RESCHEDULED', name='orderstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drop_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_log',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='notificationstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_order_id'), 'notifications_log', ['order_id'], unique=False)
    op.create_table('reschedule_requests',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reschedule_requests_order_id'), 'reschedule_requests', ['order_id'], unique=False)
    op.create_table('status_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'RESCHEDULED', name='orderstatus'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_order_id'), 'status_history', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_order_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_reschedule_requests_order_id'), table_name='reschedule_requests')
    op.drop_table('reschedule_requests')
    op.drop_index(op.f('ix_notifications_log_order_id'), table_name='notifications_log')
    op.drop_table('notifications_log')
    op.drop_table('orders')
    op.drop_index(op.f('ix_zone_pincodes_pincode'), table_name='zone_pincodes')
    op.drop_table('zone_pincodes')
    op.drop_table('rate_cards')
    op.drop_table('agents')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cod_surcharge_config')
    # ### end Alembic commands ###